name: air_quality
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - libffi=3.4.4
  - openssl=3.0.13
  - pip=24.0
  - python=3.11.9
  - setuptools=69.5.1
  - sqlite=3.45.3
  - tk=8.6.14
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - blinker==1.8.2
      - branca==0.7.2
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - click==8.1.7
      - colorama==0.4.6
      - contourpy==1.2.1
      - cycler==0.12.1
      - dash==2.17.0
      - dash-bootstrap-components==1.6.0
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - et-xmlfile==1.1.0
      - flask==3.0.3
      - folium==0.16.0
      - fonttools==4.52.1
      - idna==3.7
      - importlib-metadata==7.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.9.0
      - nest-asyncio==1.6.0
      - numpy==1.26.4
      - openpyxl==3.1.2
      - packaging==24.0
      - pandas==2.2.2
      - pillow==10.3.0
      - plotly==5.22.0
      - pyparsing==3.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - regex==2024.5.15
      - requests==2.32.2
      - retrying==1.3.4
      - six==1.16.0
      - tenacity==8.3.0
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - urllib3==2.2.1
      - werkzeug==3.0.3
      - xyzservices==2024.4.0
      - zipp==3.18.2


